name: flutter_slicing
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.1
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.3
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/burger.jpg
    - assets/teh.jpg
    - assets/nah.png
    - assets/

flutter_native_splash:
  color: "#ffffff" # Warna background splash screen
  image: assets/nah.png # Lokasi gambar logo splash
  android: true
  ios: true
